; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 629
global g_ImportsGameVersionPostFix64 := ".1"
=======
global g_ImportsGameVersion64 := 630
global g_ImportsGameVersionPostFix64 := ""
global g_ImportsGameVersionPlatform64 := "Steam"
>>>>>>> revertBranch
